#!/usr/bin/env bash
#Install nginx web server
sudo apt-get update -y
sudo apt-get install -y nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo nginx -t
sudo service nginx reload
