#!/usr/bin/env bash
#Double the number of webservers
sudo apt-get update
sudo apt-get install software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.4 -y
sudo apt-get update
sudo apt-get install haproxy=2.4.\* -y
sudo echo "frontend web-front
        bind *:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        server web-01 100.26.163.63:80 check
        server web-02 54.175.146.216:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
