#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.
# remove the default Nginx configuration file
rm /etc/nginx/sites-enabled/default
# Configure Nginx to listen on port 80 for all active IPv4 IPs
In -s /etc/nginx/siteg-available/default /etc/nginx/siteg-enabled/default
# restart nginx
service nginx restart
